#!/bin/bash
set -euo pipefail
rm -rf /workspace/exercise /workspace/solution
cp -r /workspace/workshop/4_local_activities/exercise /workspace/exercise
cp -r /workspace/workshop/4_local_activities/solution /workspace/solution
echo "Exercise 4 ready."
